// <auto-generated />
namespace MvcEF_crud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class StudentTableUpdatedinColAge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentTableUpdatedinColAge));
        
        string IMigrationMetadata.Id
        {
            get { return "202511180435318_StudentTableUpdatedinColAge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
