// <auto-generated />
namespace SMSLite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class course_enrolment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(course_enrolment));
        
        string IMigrationMetadata.Id
        {
            get { return "202511200903091_course_enrolment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
